/* Malaysian universities & institutes — researched data (QS 2026). */
const UNIVERSITIES = [
  {
    id: "um", name: "Universiti Malaya (UM)", icon: "🏛️", type: "public",
    city: "Kuala Lumpur", state: "WP Kuala Lumpur", qs: 58, est: 1905,
    tuition: "RM 13,000–35,000", website: "https://www.um.edu.my",
    intakes: ["February", "July"], offerLetterFee: "Free",
    ielts: "6.0 (UG) / 6.5 (PG)", locations: ["Kuala Lumpur"],
    about: "Universiti Malaya (UM) is Malaysia's oldest and highest-ranked university, ranked #58 in the QS World University Rankings 2026. Established in 1905, UM is a leading research university offering world-class education across medicine, engineering, law, and the sciences.",
    facilities: ["Medical Centre","Research Institutes","Library","Sports Complex","Student Residences","International Student Centre"],
    fields: ["Medicine","Engineering","Law","Sciences"],
    programs: [
      { name: "Bachelor of Medicine & Bachelor of Surgery (MBBS)", level: "Bachelor", field: "Medicine", fee: 35000, duration: 5, campus: "Kuala Lumpur" },
      { name: "Bachelor of Science (Hons.) Computer Science", level: "Bachelor", field: "Computer Science & IT", fee: 16000, duration: 4, campus: "Kuala Lumpur" },
      { name: "Bachelor of Engineering (Hons.) Civil", level: "Bachelor", field: "Engineering", fee: 18000, duration: 4, campus: "Kuala Lumpur" },
      { name: "Bachelor of Laws (LLB) (Hons.)", level: "Bachelor", field: "Law", fee: 15000, duration: 3, campus: "Kuala Lumpur" },
      { name: "Bachelor of Economics (Hons.)", level: "Bachelor", field: "Business & Management", fee: 14000, duration: 3, campus: "Kuala Lumpur" },
      { name: "Bachelor of Dentistry", level: "Bachelor", field: "Medicine", fee: 30000, duration: 5, campus: "Kuala Lumpur" },
      { name: "Bachelor of Pharmacy (Hons.)", level: "Bachelor", field: "Medicine", fee: 20000, duration: 4, campus: "Kuala Lumpur" },
      { name: "Bachelor of Arts (Hons.) in History", level: "Bachelor", field: "Arts & Social Sciences", fee: 13000, duration: 3, campus: "Kuala Lumpur" },
      { name: "Master of Business Administration (MBA)", level: "Master", field: "Business & Management", fee: 22000, duration: 1.5, campus: "Kuala Lumpur" },
      { name: "Master of Science in Computer Science", level: "Master", field: "Computer Science & IT", fee: 18000, duration: 1.5, campus: "Kuala Lumpur" },
      { name: "Master of Laws (LLM)", level: "Master", field: "Law", fee: 16000, duration: 1.5, campus: "Kuala Lumpur" },
      { name: "Doctor of Philosophy (Engineering)", level: "PhD", field: "Engineering", fee: 10000, duration: 3, campus: "Kuala Lumpur" },
      { name: "Doctor of Philosophy (Medicine)", level: "PhD", field: "Medicine", fee: 10000, duration: 3, campus: "Kuala Lumpur" },
    ]
  },
  {
    id: "ukm", name: "Universiti Kebangsaan Malaysia (UKM)", icon: "🎓", type: "public",
    city: "Bangi", state: "Selangor", qs: 126, est: 1970,
    tuition: "RM 12,000–30,000", website: "https://www.ukm.my",
    intakes: ["February", "September"], offerLetterFee: "Free",
    ielts: "6.0 (UG) / 6.0 (PG)", locations: ["Bangi", "Kuala Lumpur (Medical)"],
    about: "UKM, established in 1970, is Malaysia's national university ranked #126 globally (QS 2026). Renowned for medicine, science, and engineering, UKM has a vibrant research community and strong international student support.",
    facilities: ["UKM Medical Centre","Research Institutes","International Student Unit","Sports Arena","Multiple Libraries","Student Hostels"],
    fields: ["Medicine","Science","Engineering","Social Sciences"],
    programs: [
      { name: "Bachelor of Medicine & Surgery (MBChB)", level: "Bachelor", field: "Medicine", fee: 30000, duration: 5, campus: "Kuala Lumpur" },
      { name: "Bachelor of Science (Hons.) Biomedical Science", level: "Bachelor", field: "Medicine", fee: 16000, duration: 3, campus: "Bangi" },
      { name: "Bachelor of Engineering (Hons.) Chemical", level: "Bachelor", field: "Engineering", fee: 17000, duration: 4, campus: "Bangi" },
      { name: "Bachelor of Computer Science (Hons.)", level: "Bachelor", field: "Computer Science & IT", fee: 15000, duration: 4, campus: "Bangi" },
      { name: "Bachelor of Social Science (Hons.) Political Science", level: "Bachelor", field: "Arts & Social Sciences", fee: 12000, duration: 3, campus: "Bangi" },
      { name: "Bachelor of Laws (LLB) (Hons.)", level: "Bachelor", field: "Law", fee: 14000, duration: 3, campus: "Bangi" },
      { name: "Bachelor of Dentistry", level: "Bachelor", field: "Medicine", fee: 28000, duration: 5, campus: "Kuala Lumpur" },
      { name: "Master of Business Administration", level: "Master", field: "Business & Management", fee: 20000, duration: 1.5, campus: "Bangi" },
      { name: "Master of Science (Bioinformatics)", level: "Master", field: "Computer Science & IT", fee: 16000, duration: 1.5, campus: "Bangi" },
      { name: "Doctor of Philosophy (Chemistry)", level: "PhD", field: "Natural Sciences", fee: 9000, duration: 3, campus: "Bangi" },
    ]
  },
  {
    id: "upm", name: "Universiti Putra Malaysia (UPM)", icon: "🌿", type: "public",
    city: "Serdang", state: "Selangor", qs: 134, est: 1931,
    tuition: "RM 12,000–28,000", website: "https://www.upm.edu.my",
    intakes: ["March", "September"], offerLetterFee: "Free",
    ielts: "5.5 (UG) / 6.0 (PG)", locations: ["Serdang", "Bintulu (Sarawak Campus)"],
    about: "UPM, ranked #134 globally (QS 2026), is Malaysia's premier agricultural and research university. Founded in 1931, it excels in life sciences, agriculture, veterinary science, and engineering.",
    facilities: ["Teaching Hospital","Veterinary Clinic","Agro-Technology Park","Forest Research Institute","Sports Complex","International Student Centre"],
    fields: ["Agriculture","Veterinary","Forestry","Engineering"],
    programs: [
      { name: "Bachelor of Agricultural Science (Hons.)", level: "Bachelor", field: "Agriculture & Forestry", fee: 13000, duration: 4, campus: "Serdang" },
      { name: "Bachelor of Veterinary Medicine", level: "Bachelor", field: "Medicine", fee: 25000, duration: 5, campus: "Serdang" },
      { name: "Bachelor of Engineering (Hons.) Aerospace", level: "Bachelor", field: "Engineering", fee: 18000, duration: 4, campus: "Serdang" },
      { name: "Bachelor of Science (Hons.) Environmental Science", level: "Bachelor", field: "Natural Sciences", fee: 14000, duration: 3, campus: "Serdang" },
      { name: "Bachelor of Computer Science (Hons.)", level: "Bachelor", field: "Computer Science & IT", fee: 14000, duration: 4, campus: "Serdang" },
      { name: "Bachelor of Forestry Science (Hons.)", level: "Bachelor", field: "Agriculture & Forestry", fee: 13000, duration: 4, campus: "Serdang" },
      { name: "Bachelor of Nutrition & Dietetics (Hons.)", level: "Bachelor", field: "Medicine", fee: 15000, duration: 4, campus: "Serdang" },
      { name: "Master of Agribusiness", level: "Master", field: "Business & Management", fee: 17000, duration: 1.5, campus: "Serdang" },
      { name: "Master of Science (Animal Science)", level: "Master", field: "Agriculture & Forestry", fee: 14000, duration: 1.5, campus: "Serdang" },
      { name: "Doctor of Philosophy (Environmental Science)", level: "PhD", field: "Natural Sciences", fee: 9000, duration: 3, campus: "Serdang" },
    ]
  },
  {
    id: "usm", name: "Universiti Sains Malaysia (USM)", icon: "🔬", type: "public",
    city: "Gelugor", state: "Penang", qs: 134, est: 1969,
    tuition: "RM 12,000–30,000", website: "https://www.usm.my",
    intakes: ["February", "September"], offerLetterFee: "Free",
    ielts: "5.5 (UG) / 6.0 (PG)", locations: ["Penang", "Kubang Kerian (Health Campus)", "Nibong Tebal (Engineering Campus)"],
    about: "USM is a APEX (Accelerated Programme for Excellence) university ranked #134 globally (QS 2026). Based in Penang, USM is renowned for pharmacy, medicine, sciences and engineering across three campuses.",
    facilities: ["Hospital USM","Pharmacy Laboratories","Engineering Campus","Science Labs","International Mobility Unit","Cultural Centre"],
    fields: ["Pharmacy","Medicine","Sciences","Engineering"],
    programs: [
      { name: "Bachelor of Pharmacy (Hons.)", level: "Bachelor", field: "Medicine", fee: 22000, duration: 4, campus: "Penang" },
      { name: "Bachelor of Medicine, Bachelor of Surgery (MBChB)", level: "Bachelor", field: "Medicine", fee: 28000, duration: 5, campus: "Kubang Kerian" },
      { name: "Bachelor of Engineering (Hons.) Mechanical", level: "Bachelor", field: "Engineering", fee: 16000, duration: 4, campus: "Nibong Tebal" },
      { name: "Bachelor of Science (Hons.) Physics", level: "Bachelor", field: "Natural Sciences", fee: 13000, duration: 3, campus: "Penang" },
      { name: "Bachelor of Science (Hons.) Chemistry", level: "Bachelor", field: "Natural Sciences", fee: 13000, duration: 3, campus: "Penang" },
      { name: "Bachelor of Computer Science (Hons.)", level: "Bachelor", field: "Computer Science & IT", fee: 14000, duration: 4, campus: "Penang" },
      { name: "Master of Science in Drug Technology", level: "Master", field: "Medicine", fee: 17000, duration: 1.5, campus: "Penang" },
      { name: "Master of Business Administration", level: "Master", field: "Business & Management", fee: 19000, duration: 1.5, campus: "Penang" },
      { name: "Doctor of Philosophy (Pharmaceutical Sciences)", level: "PhD", field: "Medicine", fee: 9500, duration: 3, campus: "Penang" },
    ]
  },
  {
    id: "utm", name: "Universiti Teknologi Malaysia (UTM)", icon: "⚙️", type: "public",
    city: "Johor Bahru", state: "Johor", qs: 153, est: 1904,
    tuition: "RM 12,000–28,000", website: "https://www.utm.my",
    intakes: ["February", "September"], offerLetterFee: "Free",
    ielts: "5.5 (UG) / 6.0 (PG)", locations: ["Johor Bahru", "Kuala Lumpur (City Campus)"],
    about: "UTM, ranked #153 globally (QS 2026), is Malaysia's leading technical university. With over 120 years of history, UTM is renowned for engineering, architecture, computing and built environment programs.",
    facilities: ["Engineering Labs","Architecture Studio","Advanced Computing Centre","Sports Complex","International Office","Student Innovation Hub"],
    fields: ["Engineering","Architecture","Computing","Built Environment"],
    programs: [
      { name: "Bachelor of Engineering (Hons.) Civil", level: "Bachelor", field: "Engineering", fee: 16000, duration: 4, campus: "Johor Bahru" },
      { name: "Bachelor of Engineering (Hons.) Electrical", level: "Bachelor", field: "Engineering", fee: 16000, duration: 4, campus: "Johor Bahru" },
      { name: "Bachelor of Architecture (Hons.)", level: "Bachelor", field: "Architecture & Built Environment", fee: 17000, duration: 5, campus: "Johor Bahru" },
      { name: "Bachelor of Computer Science (Hons.) Network Security", level: "Bachelor", field: "Computer Science & IT", fee: 15000, duration: 4, campus: "Johor Bahru" },
      { name: "Bachelor of Science (Hons.) Quantity Surveying", level: "Bachelor", field: "Architecture & Built Environment", fee: 15000, duration: 4, campus: "Johor Bahru" },
      { name: "Bachelor of Engineering (Hons.) Chemical", level: "Bachelor", field: "Engineering", fee: 17000, duration: 4, campus: "Johor Bahru" },
      { name: "Bachelor of Engineering (Hons.) Software", level: "Bachelor", field: "Computer Science & IT", fee: 16000, duration: 4, campus: "Kuala Lumpur" },
      { name: "Master of Engineering (Mechanical)", level: "Master", field: "Engineering", fee: 18000, duration: 1.5, campus: "Johor Bahru" },
      { name: "Master of Business Administration", level: "Master", field: "Business & Management", fee: 20000, duration: 1.5, campus: "Kuala Lumpur" },
      { name: "Doctor of Philosophy (Civil Engineering)", level: "PhD", field: "Engineering", fee: 9000, duration: 3, campus: "Johor Bahru" },
    ]
  },
  {
    id: "uitm", name: "Universiti Teknologi MARA (UiTM)", icon: "📐", type: "public",
    city: "Shah Alam", state: "Selangor", qs: null, est: 1956,
    tuition: "RM 10,000–25,000", website: "https://www.uitm.edu.my",
    intakes: ["March", "September"], offerLetterFee: "Free",
    ielts: "5.0 (UG) / 5.5 (PG)", locations: ["Shah Alam","Multiple branch campuses across Malaysia"],
    about: "UiTM is Malaysia's largest university with 40+ campuses nationwide. Established in 1956, it offers diverse programs in business, law, art, design and technology.",
    facilities: ["Multiple Libraries","Art Galleries","Legal Aid Clinics","Media Studios","Sports Facilities","Student Residences"],
    fields: ["Business","Law","Art & Design","Mass Communication"],
    programs: [
      { name: "Bachelor of Business Administration (Hons.)", level: "Bachelor", field: "Business & Management", fee: 12000, duration: 3, campus: "Shah Alam" },
      { name: "Bachelor of Laws (Hons.)", level: "Bachelor", field: "Law", fee: 13000, duration: 3, campus: "Shah Alam" },
      { name: "Bachelor of Arts (Hons.) in Fine Arts", level: "Bachelor", field: "Art & Design", fee: 11000, duration: 3, campus: "Shah Alam" },
      { name: "Bachelor of Mass Communication (Hons.) Broadcasting", level: "Bachelor", field: "Communication & Media", fee: 12000, duration: 3, campus: "Shah Alam" },
      { name: "Diploma in Computer Science", level: "Diploma", field: "Computer Science & IT", fee: 8000, duration: 2.5, campus: "Shah Alam" },
      { name: "Diploma in Accounting", level: "Diploma", field: "Business & Management", fee: 7500, duration: 2.5, campus: "Shah Alam" },
      { name: "Bachelor of Accountancy (Hons.)", level: "Bachelor", field: "Business & Management", fee: 13000, duration: 3, campus: "Shah Alam" },
      { name: "Master of Business Administration", level: "Master", field: "Business & Management", fee: 18000, duration: 1.5, campus: "Shah Alam" },
    ]
  },
  {
    id: "iium", name: "International Islamic University Malaysia (IIUM)", icon: "🕌", type: "public",
    city: "Gombak", state: "Selangor", qs: null, est: 1983,
    tuition: "RM 11,000–30,000", website: "https://www.iium.edu.my",
    intakes: ["March", "September"], offerLetterFee: "Free",
    ielts: "5.5 (UG) / 6.0 (PG)", locations: ["Gombak","Kuantan (Medical & Dental)","Petaling Jaya (Law)"],
    about: "IIUM is a unique Islamic international university established in 1983, offering programs that integrate Islamic values with modern knowledge. It serves students from 100+ countries.",
    facilities: ["Medical & Dental Faculty","Law Academy","Mosque","Arabic Language Centre","International Student Division","Cultural Village"],
    fields: ["Islamic Studies","Law","Medicine","Economics"],
    programs: [
      { name: "Bachelor of Medicine, Bachelor of Surgery (MBBS)", level: "Bachelor", field: "Medicine", fee: 28000, duration: 5, campus: "Kuantan" },
      { name: "Bachelor of Dental Surgery (BDS)", level: "Bachelor", field: "Medicine", fee: 26000, duration: 5, campus: "Kuantan" },
      { name: "Bachelor of Laws (Hons.) Civil Law", level: "Bachelor", field: "Law", fee: 14000, duration: 3, campus: "Petaling Jaya" },
      { name: "Bachelor of Shariah (Hons.)", level: "Bachelor", field: "Islamic Studies", fee: 11000, duration: 3, campus: "Gombak" },
      { name: "Bachelor of Economics (Hons.) Islamic Economics", level: "Bachelor", field: "Business & Management", fee: 12000, duration: 3, campus: "Gombak" },
      { name: "Bachelor of Engineering (Hons.) Mechatronics", level: "Bachelor", field: "Engineering", fee: 17000, duration: 4, campus: "Gombak" },
      { name: "Bachelor of Human Sciences (Hons.) Psychology", level: "Bachelor", field: "Arts & Social Sciences", fee: 13000, duration: 3, campus: "Gombak" },
      { name: "Master of Business Administration (Islamic Banking)", level: "Master", field: "Business & Management", fee: 19000, duration: 1.5, campus: "Gombak" },
      { name: "Doctor of Philosophy (Islamic Studies)", level: "PhD", field: "Islamic Studies", fee: 9000, duration: 3, campus: "Gombak" },
    ]
  },
  {
    id: "uum", name: "Universiti Utara Malaysia (UUM)", icon: "📊", type: "public",
    city: "Sintok", state: "Kedah", qs: null, est: 1984,
    tuition: "RM 10,000–22,000", website: "https://www.uum.edu.my",
    intakes: ["February", "September"], offerLetterFee: "Free",
    ielts: "5.0 (UG) / 5.5 (PG)", locations: ["Sintok","Kuala Lumpur (Graduate School)"],
    about: "UUM is Malaysia's management university, established in 1984. It is recognised for business, accountancy, economics and IT programs, and operates Malaysia's largest residential campus.",
    facilities: ["Business School","IT Labs","Golf Course","Hotel School","Sports Complex","International Village"],
    fields: ["Business","Management","Economics","IT"],
    programs: [
      { name: "Bachelor of Business Administration (Hons.)", level: "Bachelor", field: "Business & Management", fee: 11000, duration: 3, campus: "Sintok" },
      { name: "Bachelor of Accountancy (Hons.)", level: "Bachelor", field: "Business & Management", fee: 11000, duration: 3, campus: "Sintok" },
      { name: "Bachelor of Science (Hons.) Information Technology", level: "Bachelor", field: "Computer Science & IT", fee: 12000, duration: 3, campus: "Sintok" },
      { name: "Bachelor of Economics (Hons.)", level: "Bachelor", field: "Business & Management", fee: 10000, duration: 3, campus: "Sintok" },
      { name: "Diploma in Business Administration", level: "Diploma", field: "Business & Management", fee: 7000, duration: 2.5, campus: "Sintok" },
      { name: "Master of Business Administration", level: "Master", field: "Business & Management", fee: 17000, duration: 1.5, campus: "Sintok" },
      { name: "Doctor of Philosophy (Management)", level: "PhD", field: "Business & Management", fee: 8500, duration: 3, campus: "Sintok" },
    ]
  },
  {
    id: "taylor", name: "Taylor's University", icon: "🏅", type: "private",
    city: "Subang Jaya", state: "Selangor", qs: 253, est: 1969,
    tuition: "RM 28,000–70,000", website: "https://university.taylors.edu.my",
    intakes: ["February", "May", "August"], offerLetterFee: "Free",
    ielts: "5.5 (UG) / 6.0 (PG)", locations: ["Subang Jaya"],
    about: "Taylor's University, ranked #253 globally (QS 2026), is Malaysia's #1 private university and a QS 5-Star university. Established in 1969, Taylor's is renowned for hospitality, culinary arts, medicine and business.",
    facilities: ["Culinary & Hospitality Lab","Simulation Medical Lab","Design Studio","Taylor's Lake","Sports Centre","Taylor's International School Partnership"],
    fields: ["Hospitality","Business","Medicine","Design"],
    programs: [
      { name: "Bachelor of Medicine, Bachelor of Surgery (MBBCh BAO)", level: "Bachelor", field: "Medicine", fee: 70000, duration: 5, campus: "Subang Jaya" },
      { name: "Bachelor of Culinary Arts (Hons.)", level: "Bachelor", field: "Hospitality & Tourism", fee: 38000, duration: 3, campus: "Subang Jaya" },
      { name: "Bachelor of International Hospitality Management (Hons.)", level: "Bachelor", field: "Hospitality & Tourism", fee: 35000, duration: 3, campus: "Subang Jaya" },
      { name: "Bachelor of Business Administration (Hons.)", level: "Bachelor", field: "Business & Management", fee: 32000, duration: 3, campus: "Subang Jaya" },
      { name: "Bachelor of Laws (Hons.) LLB", level: "Bachelor", field: "Law", fee: 40000, duration: 3, campus: "Subang Jaya" },
      { name: "Bachelor of Architecture (Hons.)", level: "Bachelor", field: "Architecture & Built Environment", fee: 38000, duration: 5, campus: "Subang Jaya" },
      { name: "Bachelor of Computer Science (Hons.) Cybersecurity", level: "Bachelor", field: "Computer Science & IT", fee: 36000, duration: 3, campus: "Subang Jaya" },
      { name: "Bachelor of Pharmacy (Hons.)", level: "Bachelor", field: "Medicine", fee: 45000, duration: 4, campus: "Subang Jaya" },
      { name: "Diploma in Culinary Arts", level: "Diploma", field: "Hospitality & Tourism", fee: 25000, duration: 1.5, campus: "Subang Jaya" },
      { name: "Foundation in Natural & Built Environment", level: "Foundation", field: "Architecture & Built Environment", fee: 28000, duration: 1, campus: "Subang Jaya" },
      { name: "Master of Business Administration", level: "Master", field: "Business & Management", fee: 45000, duration: 1.5, campus: "Subang Jaya" },
      { name: "Master of Architecture", level: "Master", field: "Architecture & Built Environment", fee: 38000, duration: 2, campus: "Subang Jaya" },
    ]
  },
  {
    id: "sunway", name: "Sunway University", icon: "🌟", type: "private",
    city: "Bandar Sunway", state: "Selangor", qs: 410, est: 2004,
    tuition: "RM 25,000–60,000", website: "https://university.sunway.edu.my",
    intakes: ["February", "June", "September"], offerLetterFee: "Free",
    ielts: "5.5 (UG) / 6.0 (PG)", locations: ["Bandar Sunway"],
    about: "Sunway University, ranked #410 globally (QS 2026), is a premier private university known for actuarial science, business and hospitality. It rose 129 places in 2026, making it one of Malaysia's fastest-improving institutions.",
    facilities: ["Actuarial Lab","Sunway Medical Centre","Hospitality Kitchen","e-Sports Centre","Art Gallery","Library & Learning Commons"],
    fields: ["Business","Actuarial Science","Hospitality","Psychology"],
    programs: [
      { name: "Bachelor of Science (Hons.) Actuarial Studies", level: "Bachelor", field: "Business & Management", fee: 38000, duration: 3, campus: "Bandar Sunway" },
      { name: "Bachelor of Business Administration (Hons.) Finance", level: "Bachelor", field: "Business & Management", fee: 30000, duration: 3, campus: "Bandar Sunway" },
      { name: "Bachelor of Accounting (Hons.)", level: "Bachelor", field: "Business & Management", fee: 29000, duration: 3, campus: "Bandar Sunway" },
      { name: "Bachelor of Psychology (Hons.)", level: "Bachelor", field: "Arts & Social Sciences", fee: 28000, duration: 3, campus: "Bandar Sunway" },
      { name: "Bachelor of International Hospitality Management (Hons.)", level: "Bachelor", field: "Hospitality & Tourism", fee: 32000, duration: 3, campus: "Bandar Sunway" },
      { name: "Bachelor of Computer Science (Hons.) Data Science", level: "Bachelor", field: "Computer Science & IT", fee: 30000, duration: 3, campus: "Bandar Sunway" },
      { name: "Bachelor of Laws (Hons.)", level: "Bachelor", field: "Law", fee: 35000, duration: 3, campus: "Bandar Sunway" },
      { name: "Foundation in Business", level: "Foundation", field: "Business & Management", fee: 22000, duration: 1, campus: "Bandar Sunway" },
      { name: "Master of Business Administration", level: "Master", field: "Business & Management", fee: 40000, duration: 1.5, campus: "Bandar Sunway" },
      { name: "Master of Science in Actuarial Science", level: "Master", field: "Business & Management", fee: 35000, duration: 1.5, campus: "Bandar Sunway" },
    ]
  },
  {
    id: "ucsi", name: "UCSI University", icon: "🎵", type: "private",
    city: "Kuala Lumpur", state: "WP Kuala Lumpur", qs: 265, est: 1986,
    tuition: "RM 22,000–55,000", website: "https://www.ucsiuniversity.edu.my",
    intakes: ["February", "May", "September"], offerLetterFee: "Free",
    ielts: "5.5 (UG) / 6.0 (PG)", locations: ["Kuala Lumpur","Springhill (Negeri Sembilan)","Sarawak Campus"],
    about: "UCSI University, ranked #265 globally (QS 2026), is known for its unique music conservatory, medicine, pharmacy, and engineering. Students from 100+ countries study at its three campuses.",
    facilities: ["UCSI Hospital","Music Conservatory","Pharmacy Labs","Engineering Labs","Hospitality Kitchen","Multiple Campus Libraries"],
    fields: ["Music","Pharmacy","Engineering","Medicine"],
    programs: [
      { name: "Bachelor of Medicine, Bachelor of Surgery (MBChB)", level: "Bachelor", field: "Medicine", fee: 55000, duration: 5, campus: "Kuala Lumpur" },
      { name: "Bachelor of Pharmacy (Hons.)", level: "Bachelor", field: "Medicine", fee: 38000, duration: 4, campus: "Kuala Lumpur" },
      { name: "Bachelor of Music (Hons.)", level: "Bachelor", field: "Art & Design", fee: 28000, duration: 4, campus: "Kuala Lumpur" },
      { name: "Bachelor of Engineering (Hons.) Chemical", level: "Bachelor", field: "Engineering", fee: 30000, duration: 4, campus: "Kuala Lumpur" },
      { name: "Bachelor of Computer Science (Hons.)", level: "Bachelor", field: "Computer Science & IT", fee: 26000, duration: 3, campus: "Kuala Lumpur" },
      { name: "Bachelor of Nursing (Hons.)", level: "Bachelor", field: "Medicine", fee: 32000, duration: 4, campus: "Kuala Lumpur" },
      { name: "Bachelor of Architecture (Hons.)", level: "Bachelor", field: "Architecture & Built Environment", fee: 34000, duration: 5, campus: "Kuala Lumpur" },
      { name: "Bachelor of Business Administration (Hons.) Marketing", level: "Bachelor", field: "Business & Management", fee: 25000, duration: 3, campus: "Kuala Lumpur" },
      { name: "Diploma in Music", level: "Diploma", field: "Art & Design", fee: 18000, duration: 2.5, campus: "Kuala Lumpur" },
      { name: "Master of Business Administration", level: "Master", field: "Business & Management", fee: 35000, duration: 1.5, campus: "Kuala Lumpur" },
      { name: "Doctor of Philosophy (Engineering)", level: "PhD", field: "Engineering", fee: 15000, duration: 3, campus: "Kuala Lumpur" },
    ]
  },
  {
    id: "utp", name: "Universiti Teknologi PETRONAS (UTP)", icon: "🛢️", type: "private",
    city: "Seri Iskandar", state: "Perak", qs: 251, est: 1997,
    tuition: "RM 30,000–45,000", website: "https://www.utp.edu.my",
    intakes: ["January", "July"], offerLetterFee: "Free",
    ielts: "6.0 (UG) / 6.5 (PG)", locations: ["Seri Iskandar, Perak"],
    about: "UTP, ranked #251 globally (QS 2026), is one of Asia's top engineering universities, established by PETRONAS in 1997. World-renowned for petroleum, chemical, and mechanical engineering with state-of-the-art research facilities.",
    facilities: ["Offshore Structure Lab","Petroleum Research Lab","Smart Village","Sports Complex","Residence Colleges","Career Services"],
    fields: ["Petroleum Engineering","Chemical Engineering","Geoscience","IT"],
    programs: [
      { name: "Bachelor of Engineering (Hons.) Petroleum Engineering", level: "Bachelor", field: "Engineering", fee: 45000, duration: 4, campus: "Seri Iskandar" },
      { name: "Bachelor of Engineering (Hons.) Chemical Engineering", level: "Bachelor", field: "Engineering", fee: 40000, duration: 4, campus: "Seri Iskandar" },
      { name: "Bachelor of Engineering (Hons.) Mechanical Engineering", level: "Bachelor", field: "Engineering", fee: 40000, duration: 4, campus: "Seri Iskandar" },
      { name: "Bachelor of Science (Hons.) Geoscience", level: "Bachelor", field: "Natural Sciences", fee: 35000, duration: 4, campus: "Seri Iskandar" },
      { name: "Bachelor of Technology (Hons.) Information Technology", level: "Bachelor", field: "Computer Science & IT", fee: 32000, duration: 4, campus: "Seri Iskandar" },
      { name: "Bachelor of Engineering (Hons.) Electrical & Electronic", level: "Bachelor", field: "Engineering", fee: 40000, duration: 4, campus: "Seri Iskandar" },
      { name: "Master of Science in Petroleum Engineering", level: "Master", field: "Engineering", fee: 35000, duration: 1.5, campus: "Seri Iskandar" },
      { name: "Doctor of Philosophy (Chemical Engineering)", level: "PhD", field: "Engineering", fee: 18000, duration: 3, campus: "Seri Iskandar" },
    ]
  },
  {
    id: "mmu", name: "Multimedia University (MMU)", icon: "💻", type: "private",
    city: "Cyberjaya", state: "Selangor", qs: null, est: 1996,
    tuition: "RM 20,000–40,000", website: "https://www.mmu.edu.my",
    intakes: ["March", "July", "October"], offerLetterFee: "Free",
    ielts: "5.0 (UG) / 5.5 (PG)", locations: ["Cyberjaya","Melaka"],
    about: "MMU is Malaysia's first private university approved by the Malaysian government, established in 1996. Top-ranked for ICT employment, MMU offers cutting-edge programs in computing, engineering, creative multimedia and business.",
    facilities: ["Creative Lab","Animation Studio","Engineering Labs","Game Development Centre","Cyberjaya Tech Ecosystem","Student Residences"],
    fields: ["IT","Engineering","Creative Multimedia","Business"],
    programs: [
      { name: "Bachelor of Computer Science (Hons.) Software Engineering", level: "Bachelor", field: "Computer Science & IT", fee: 25750, duration: 3, campus: "Cyberjaya" },
      { name: "Bachelor of Computer Science (Hons.) Artificial Intelligence", level: "Bachelor", field: "Computer Science & IT", fee: 25750, duration: 3, campus: "Cyberjaya" },
      { name: "Bachelor of Computer Science (Hons.) Cybersecurity", level: "Bachelor", field: "Computer Science & IT", fee: 25750, duration: 3, campus: "Cyberjaya" },
      { name: "Bachelor of Information Technology (Hons.) Networking", level: "Bachelor", field: "Computer Science & IT", fee: 24000, duration: 3, campus: "Cyberjaya" },
      { name: "Bachelor of Engineering (Hons.) Electronics", level: "Bachelor", field: "Engineering", fee: 28000, duration: 4, campus: "Cyberjaya" },
      { name: "Bachelor of Engineering (Hons.) Mechatronics", level: "Bachelor", field: "Engineering", fee: 28000, duration: 4, campus: "Cyberjaya" },
      { name: "Bachelor of Multimedia (Hons.) Animation", level: "Bachelor", field: "Art & Design", fee: 26000, duration: 3, campus: "Cyberjaya" },
      { name: "Bachelor of Multimedia (Hons.) Digital Media", level: "Bachelor", field: "Art & Design", fee: 26000, duration: 3, campus: "Cyberjaya" },
      { name: "Bachelor of Business Administration (Hons.)", level: "Bachelor", field: "Business & Management", fee: 22000, duration: 3, campus: "Cyberjaya" },
      { name: "Bachelor of Mass Communication (Hons.)", level: "Bachelor", field: "Communication & Media", fee: 22000, duration: 3, campus: "Cyberjaya" },
      { name: "Diploma in Information Technology", level: "Diploma", field: "Computer Science & IT", fee: 14000, duration: 2, campus: "Melaka" },
      { name: "Master of Science in Computer Science", level: "Master", field: "Computer Science & IT", fee: 23600, duration: 1.5, campus: "Cyberjaya" },
      { name: "Master of Business Administration", level: "Master", field: "Business & Management", fee: 23600, duration: 1, campus: "Cyberjaya" },
      { name: "Doctor of Philosophy (Engineering)", level: "PhD", field: "Engineering", fee: 6375, duration: 2, campus: "Cyberjaya" },
    ]
  },
  {
    id: "apu", name: "Asia Pacific University (APU)", icon: "🖥️", type: "private",
    city: "Kuala Lumpur", state: "WP Kuala Lumpur", qs: null, est: 1993,
    tuition: "RM 22,000–45,000", website: "https://www.apu.edu.my",
    intakes: ["February", "May", "September"], offerLetterFee: "Free",
    ielts: "5.5 (UG) / 6.0 (PG)", locations: ["Kuala Lumpur"],
    about: "APU is the #1 choice for international students in Malaysia, hosting students from 130+ countries. Established in 1993, APU is renowned for computing, IT, cybersecurity, and business programs.",
    facilities: ["Technology Innovation Centre","Cybersecurity Lab","Startup Incubator","e-Sports Arena","Student Village","International Student Office"],
    fields: ["Computing","IT","Cybersecurity","Business"],
    programs: [
      { name: "Bachelor of Computer Science (Hons.) in Cybersecurity", level: "Bachelor", field: "Computer Science & IT", fee: 32000, duration: 3, campus: "Kuala Lumpur" },
      { name: "Bachelor of Computer Science (Hons.) Artificial Intelligence", level: "Bachelor", field: "Computer Science & IT", fee: 32000, duration: 3, campus: "Kuala Lumpur" },
      { name: "Bachelor of Science (Hons.) Data Science & Business Analytics", level: "Bachelor", field: "Computer Science & IT", fee: 30000, duration: 3, campus: "Kuala Lumpur" },
      { name: "Bachelor of Software Engineering (Hons.)", level: "Bachelor", field: "Computer Science & IT", fee: 30000, duration: 3, campus: "Kuala Lumpur" },
      { name: "Bachelor of Business Administration (Hons.) in Finance & Banking", level: "Bachelor", field: "Business & Management", fee: 26000, duration: 3, campus: "Kuala Lumpur" },
      { name: "Bachelor of Accounting (Hons.)", level: "Bachelor", field: "Business & Management", fee: 26000, duration: 3, campus: "Kuala Lumpur" },
      { name: "Bachelor of Engineering (Hons.) Telecommunications", level: "Bachelor", field: "Engineering", fee: 33000, duration: 4, campus: "Kuala Lumpur" },
      { name: "Diploma in Information Technology", level: "Diploma", field: "Computer Science & IT", fee: 18000, duration: 2.5, campus: "Kuala Lumpur" },
      { name: "Foundation in Computing", level: "Foundation", field: "Computer Science & IT", fee: 14000, duration: 1, campus: "Kuala Lumpur" },
      { name: "Master of Science in Cyber Security", level: "Master", field: "Computer Science & IT", fee: 35000, duration: 1.5, campus: "Kuala Lumpur" },
      { name: "Doctor of Philosophy (Computing)", level: "PhD", field: "Computer Science & IT", fee: 18000, duration: 3, campus: "Kuala Lumpur" },
    ]
  },
  {
    id: "mahsa", name: "MAHSA University", icon: "🦷", type: "private",
    city: "Jenjarom", state: "Selangor", qs: null, est: 2005,
    tuition: "RM 25,000–60,000", website: "https://www.mahsa.edu.my",
    intakes: ["February", "June", "October"], offerLetterFee: "Free",
    ielts: "5.5 (UG) / 6.0 (PG)", locations: ["Jenjarom, Selangor","Kuala Lumpur (City Campus)"],
    about: "MAHSA University specialises in healthcare education, offering medicine, dentistry, nursing, pharmacy and allied health programs. Established in 2005, it has its own teaching hospital and dental clinic.",
    facilities: ["MAHSA Hospital","Dental Clinic","Pharmacy Labs","Nursing Simulation Lab","Research Centre","Student Hostels"],
    fields: ["Medicine","Dentistry","Nursing","Pharmacy"],
    programs: [
      { name: "Bachelor of Medicine, Bachelor of Surgery (MBBS)", level: "Bachelor", field: "Medicine", fee: 60000, duration: 5, campus: "Jenjarom" },
      { name: "Bachelor of Dental Surgery (BDS)", level: "Bachelor", field: "Medicine", fee: 55000, duration: 5, campus: "Jenjarom" },
      { name: "Bachelor of Pharmacy (Hons.)", level: "Bachelor", field: "Medicine", fee: 35000, duration: 4, campus: "Jenjarom" },
      { name: "Bachelor of Nursing (Hons.)", level: "Bachelor", field: "Medicine", fee: 28000, duration: 4, campus: "Jenjarom" },
      { name: "Bachelor of Medical Imaging (Hons.)", level: "Bachelor", field: "Medicine", fee: 30000, duration: 4, campus: "Jenjarom" },
      { name: "Diploma in Nursing", level: "Diploma", field: "Medicine", fee: 18000, duration: 3, campus: "Jenjarom" },
      { name: "Master of Public Health", level: "Master", field: "Medicine", fee: 30000, duration: 1.5, campus: "Jenjarom" },
    ]
  },
  {
    id: "monash", name: "Monash University Malaysia", icon: "🇦🇺", type: "branch",
    city: "Bandar Sunway", state: "Selangor", qs: 36, est: 1998,
    tuition: "RM 40,000–55,000", website: "https://www.monash.edu.my",
    intakes: ["February", "July"], offerLetterFee: "Free",
    ielts: "6.0 (UG) / 6.5 (PG)", locations: ["Bandar Sunway, Selangor"],
    about: "Monash University Malaysia is the Malaysian campus of Monash University, Australia — ranked #36 in the world (QS 2026). Established in 1998, it offers the same internationally recognised degrees as the Australian campus.",
    facilities: ["Medical Research Facilities","Engineering Labs","Arts & Social Sciences Centre","Sports Hall","International Student Centre","State-of-the-art Library"],
    fields: ["Medicine","Engineering","Business","Pharmacy"],
    programs: [
      { name: "Bachelor of Pharmacy (Hons.)", level: "Bachelor", field: "Medicine", fee: 52000, duration: 4, campus: "Bandar Sunway" },
      { name: "Bachelor of Science in Nursing (Pre-registration)", level: "Bachelor", field: "Medicine", fee: 48000, duration: 3, campus: "Bandar Sunway" },
      { name: "Bachelor of Engineering (Hons.) Biomedical", level: "Bachelor", field: "Engineering", fee: 50000, duration: 4, campus: "Bandar Sunway" },
      { name: "Bachelor of Engineering (Hons.) Chemical", level: "Bachelor", field: "Engineering", fee: 50000, duration: 4, campus: "Bandar Sunway" },
      { name: "Bachelor of Business Administration", level: "Bachelor", field: "Business & Management", fee: 44000, duration: 3, campus: "Bandar Sunway" },
      { name: "Bachelor of Computer Science (Hons.)", level: "Bachelor", field: "Computer Science & IT", fee: 46000, duration: 3, campus: "Bandar Sunway" },
      { name: "Bachelor of Arts in Criminology", level: "Bachelor", field: "Arts & Social Sciences", fee: 42000, duration: 3, campus: "Bandar Sunway" },
      { name: "Master of Business Administration", level: "Master", field: "Business & Management", fee: 55000, duration: 1.5, campus: "Bandar Sunway" },
      { name: "Doctor of Philosophy (Engineering)", level: "PhD", field: "Engineering", fee: 22000, duration: 3, campus: "Bandar Sunway" },
    ]
  },
  {
    id: "nottingham", name: "University of Nottingham Malaysia", icon: "🇬🇧", type: "branch",
    city: "Semenyih", state: "Selangor", qs: 97, est: 2000,
    tuition: "RM 38,000–55,000", website: "https://www.nottingham.edu.my",
    intakes: ["September", "January"], offerLetterFee: "Free",
    ielts: "6.0 (UG) / 6.5 (PG)", locations: ["Semenyih, Selangor"],
    about: "The University of Nottingham Malaysia is the Malaysian campus of the University of Nottingham, UK — ranked #97 globally (QS 2026). Established in 2000, it offers the same degree programmes as the UK campus.",
    facilities:["Engineering & Science Building","Business School","Biosciences Research","Sports Pavilion","Green Campus","International Student Centre"],
    fields: ["Engineering","Business","Pharmacy","Biosciences"],
    programs: [
      { name: "Bachelor of Engineering (Hons.) Chemical Engineering", level: "Bachelor", field: "Engineering", fee: 52000, duration: 4, campus: "Semenyih" },
      { name: "Bachelor of Engineering (Hons.) Civil Engineering", level: "Bachelor", field: "Engineering", fee: 50000, duration: 4, campus: "Semenyih" },
      { name: "Bachelor of Science in Pharmacy (MPharm)", level: "Bachelor", field: "Medicine", fee: 55000, duration: 4, campus: "Semenyih" },
      { name: "Bachelor of Business Administration (International Business)", level: "Bachelor", field: "Business & Management", fee: 44000, duration: 3, campus: "Semenyih" },
      { name: "Bachelor of Science in Biosciences", level: "Bachelor", field: "Natural Sciences", fee: 42000, duration: 3, campus: "Semenyih" },
      { name: "Bachelor of Science (Hons.) Computer Science", level: "Bachelor", field: "Computer Science & IT", fee: 44000, duration: 3, campus: "Semenyih" },
      { name: "Master of Business Administration", level: "Master", field: "Business & Management", fee: 55000, duration: 1.5, campus: "Semenyih" },
      { name: "Doctor of Philosophy (Engineering)", level: "PhD", field: "Engineering", fee: 20000, duration: 3, campus: "Semenyih" },
    ]
  },
  {
    id: "msu", name: "Management & Science University (MSU)", icon: "🏥", type: "private",
    city: "Shah Alam", state: "Selangor", qs: null, est: 2001,
    tuition: "RM 20,000–45,000", website: "https://www.msu.edu.my",
    intakes: ["February", "June", "October"], offerLetterFee: "Free",
    ielts: "5.0 (UG) / 5.5 (PG)", locations: ["Shah Alam, Selangor"],
    about: "MSU is a dynamic private university established in 2001, offering health sciences, business, education and IT programs. Known for its MSU Medical Centre and strong industry linkages.",
    facilities: ["MSU Medical Centre","Pharmacy Labs","Dental Clinic","Business School","IT Centres","Sports Facilities"],
    fields: ["Health Sciences","Business","Pharmacy","Nursing"],
    programs: [
      { name: "Bachelor of Medicine & Surgery (MBBS)", level: "Bachelor", field: "Medicine", fee: 45000, duration: 5, campus: "Shah Alam" },
      { name: "Bachelor of Pharmacy (Hons.)", level: "Bachelor", field: "Medicine", fee: 30000, duration: 4, campus: "Shah Alam" },
      { name: "Bachelor of Nursing (Hons.)", level: "Bachelor", field: "Medicine", fee: 25000, duration: 4, campus: "Shah Alam" },
      { name: "Bachelor of Business Administration (Hons.)", level: "Bachelor", field: "Business & Management", fee: 20000, duration: 3, campus: "Shah Alam" },
      { name: "Bachelor of Computer Science (Hons.)", level: "Bachelor", field: "Computer Science & IT", fee: 22000, duration: 3, campus: "Shah Alam" },
      { name: "Diploma in Health Sciences (Medical Laboratory)", level: "Diploma", field: "Medicine", fee: 14000, duration: 3, campus: "Shah Alam" },
      { name: "Master of Public Health", level: "Master", field: "Medicine", fee: 28000, duration: 1.5, campus: "Shah Alam" },
    ]
  },
  {
    id: "inti", name: "INTI International University", icon: "🌐", type: "private",
    city: "Nilai", state: "Negeri Sembilan", qs: null, est: 1986,
    tuition: "RM 20,000–42,000", website: "https://www.newinti.edu.my",
    intakes: ["February", "June", "October"], offerLetterFee: "Free",
    ielts: "5.5 (UG) / 6.0 (PG)", locations: ["Nilai, Negeri Sembilan","Subang Jaya","Penang"],
    about: "INTI International University, established in 1986 and part of Laureate International Universities, offers US-partnered degrees in business, engineering and biotechnology with campuses across Malaysia.",
    facilities: ["Business School","Engineering Labs","Biotech Labs","Digital Learning Centre","Student Residences","Career Development Centre"],
    fields: ["Business","Engineering","Biotechnology","Design"],
    programs: [
      { name: "Bachelor of Business Administration (Hons.)", level: "Bachelor", field: "Business & Management", fee: 26000, duration: 3, campus: "Nilai" },
      { name: "Bachelor of Engineering (Hons.) Electrical & Electronic", level: "Bachelor", field: "Engineering", fee: 30000, duration: 4, campus: "Nilai" },
      { name: "Bachelor of Biotechnology (Hons.)", level: "Bachelor", field: "Natural Sciences", fee: 28000, duration: 3, campus: "Nilai" },
      { name: "Bachelor of Computer Science (Hons.)", level: "Bachelor", field: "Computer Science & IT", fee: 27000, duration: 3, campus: "Nilai" },
      { name: "Foundation in Business & Management", level: "Foundation", field: "Business & Management", fee: 14000, duration: 1, campus: "Nilai" },
      { name: "Master of Business Administration", level: "Master", field: "Business & Management", fee: 32000, duration: 1.5, campus: "Nilai" },
    ]
  },
  {
    id: "heriotwatt", name: "Heriot-Watt University Malaysia", icon: "🇬🇧", type: "branch",
    city: "Putrajaya", state: "WP Putrajaya", qs: null, est: 2014,
    tuition: "RM 35,000–48,000", website: "https://www.hw.ac.uk/malaysia",
    intakes: ["September", "January"], offerLetterFee: "Free",
    ielts: "6.0 (UG) / 6.5 (PG)", locations: ["Putrajaya"],
    about: "Heriot-Watt University Malaysia, established in 2014, is the Malaysian campus of Heriot-Watt University, Edinburgh. Specialising in engineering, business, architecture and the social sciences, it awards the same UK degrees.",
    facilities: ["Engineering Workshops","Business Suite","Architecture Studios","Social Sciences Labs","Student Hub","Sports Facilities"],
    fields: ["Engineering","Business","Architecture","Psychology"],
    programs: [
      { name: "Bachelor of Engineering (Hons.) Mechanical", level: "Bachelor", field: "Engineering", fee: 46000, duration: 4, campus: "Putrajaya" },
      { name: "Bachelor of Engineering (Hons.) Electrical & Electronic", level: "Bachelor", field: "Engineering", fee: 46000, duration: 4, campus: "Putrajaya" },
      { name: "Bachelor of Business Administration (Hons.)", level: "Bachelor", field: "Business & Management", fee: 38000, duration: 3, campus: "Putrajaya" },
      { name: "Bachelor of Architecture (Hons.)", level: "Bachelor", field: "Architecture & Built Environment", fee: 40000, duration: 5, campus: "Putrajaya" },
      { name: "Bachelor of Science (Hons.) Psychology", level: "Bachelor", field: "Arts & Social Sciences", fee: 36000, duration: 3, campus: "Putrajaya" },
      { name: "Master of Business Administration", level: "Master", field: "Business & Management", fee: 48000, duration: 1.5, campus: "Putrajaya" },
    ]
  },
  {
    id: "xiamen", name: "Xiamen University Malaysia", icon: "🇨🇳", type: "branch",
    city: "Sepang", state: "Selangor", qs: null, est: 2016,
    tuition: "RM 24,000–46,000", website: "https://www.xmu.edu.my",
    intakes: ["September"], offerLetterFee: "Free",
    ielts: "5.5 (UG) / 6.0 (PG)", locations: ["Sepang, Selangor"],
    about: "Xiamen University Malaysia, established in 2016, is the first overseas campus of a Chinese university. Located near KLIA, it offers unique programs blending Chinese and Malaysian academic traditions.",
    facilities: ["Traditional Chinese Medicine Clinic","Research Labs","Business School","Arts Centre","Student Village","Library"],
    fields: ["Chinese Medicine","Business","Journalism","Engineering"],
    programs: [
      { name: "Bachelor of Traditional Chinese Medicine", level: "Bachelor", field: "Medicine", fee: 40000, duration: 5, campus: "Sepang" },
      { name: "Bachelor of Accountancy (Hons.)", level: "Bachelor", field: "Business & Management", fee: 28000, duration: 3, campus: "Sepang" },
      { name: "Bachelor of Business Administration (Hons.)", level: "Bachelor", field: "Business & Management", fee: 26000, duration: 3, campus: "Sepang" },
      { name: "Bachelor of Journalism (Hons.)", level: "Bachelor", field: "Communication & Media", fee: 26000, duration: 4, campus: "Sepang" },
      { name: "Bachelor of Engineering (Hons.) Electrical", level: "Bachelor", field: "Engineering", fee: 35000, duration: 4, campus: "Sepang" },
      { name: "Master of Business Administration", level: "Master", field: "Business & Management", fee: 34000, duration: 1.5, campus: "Sepang" },
    ]
  },
  {
    id: "curtin", name: "Curtin University Malaysia", icon: "🇦🇺", type: "branch",
    city: "Miri", state: "Sarawak", qs: null, est: 1999,
    tuition: "RM 32,000–48,000", website: "https://www.curtin.edu.my",
    intakes: ["February", "July"], offerLetterFee: "Free",
    ielts: "6.0 (UG) / 6.5 (PG)", locations: ["Miri, Sarawak"],
    about: "Curtin University Malaysia, established in 1999, is the Malaysian campus of Curtin University, Perth. Located in Miri, Sarawak, it offers engineering, business and health science programs with the same Australian award.",
    facilities: ["Mining Engineering Lab","Petroleum Research Centre","Business Facilities","Health Sciences Lab","Sports Hub","Student Village"],
    fields: ["Engineering","Business","Health Sciences","Geoscience"],
    programs: [
      { name: "Bachelor of Engineering (Hons.) Mining", level: "Bachelor", field: "Engineering", fee: 46000, duration: 4, campus: "Miri" },
      { name: "Bachelor of Engineering (Hons.) Chemical", level: "Bachelor", field: "Engineering", fee: 45000, duration: 4, campus: "Miri" },
      { name: "Bachelor of Business Administration", level: "Bachelor", field: "Business & Management", fee: 36000, duration: 3, campus: "Miri" },
      { name: "Bachelor of Science (Hons.) Geoscience", level: "Bachelor", field: "Natural Sciences", fee: 38000, duration: 4, campus: "Miri" },
      { name: "Bachelor of Commerce (Accounting)", level: "Bachelor", field: "Business & Management", fee: 34000, duration: 3, campus: "Miri" },
      { name: "Master of Business Administration", level: "Master", field: "Business & Management", fee: 42000, duration: 1.5, campus: "Miri" },
    ]
  },
  {
    id: "swinburne", name: "Swinburne University of Technology Sarawak", icon: "🇦🇺", type: "branch",
    city: "Kuching", state: "Sarawak", qs: null, est: 2000,
    tuition: "RM 30,000–46,000", website: "https://www.swinburne.edu.my",
    intakes: ["February", "July"], offerLetterFee: "Free",
    ielts: "6.0 (UG) / 6.5 (PG)", locations: ["Kuching, Sarawak"],
    about: "Swinburne University Sarawak, established in 2000, is the Malaysian campus of Swinburne University of Technology, Melbourne. Offering engineering, IT, business and design programs with an Australian degree.",
    facilities: ["Smart Technology Lab","Design Studio","Business Hub","Engineering Workshops","Library","Student Residences"],
    fields: ["Engineering","IT","Business","Design"],
    programs: [
      { name: "Bachelor of Engineering (Hons.) Civil & Construction", level: "Bachelor", field: "Engineering", fee: 44000, duration: 4, campus: "Kuching" },
      { name: "Bachelor of Engineering (Hons.) Electrical & Electronic", level: "Bachelor", field: "Engineering", fee: 44000, duration: 4, campus: "Kuching" },
      { name: "Bachelor of Computer Science (Hons.) Data Science", level: "Bachelor", field: "Computer Science & IT", fee: 36000, duration: 3, campus: "Kuching" },
      { name: "Bachelor of Business Administration (Hons.)", level: "Bachelor", field: "Business & Management", fee: 34000, duration: 3, campus: "Kuching" },
      { name: "Bachelor of Design (Hons.) Communication Design", level: "Bachelor", field: "Art & Design", fee: 36000, duration: 3, campus: "Kuching" },
      { name: "Master of Business Administration", level: "Master", field: "Business & Management", fee: 40000, duration: 1.5, campus: "Kuching" },
    ]
  },
  {
    id: "ums", name: "Universiti Malaysia Sabah (UMS)", icon: "🌊", type: "public",
    city: "Kota Kinabalu", state: "Sabah", qs: null, est: 1994,
    tuition: "RM 10,000–24,000", website: "https://www.ums.edu.my",
    intakes: ["February", "September"], offerLetterFee: "Free",
    ielts: "5.0 (UG) / 5.5 (PG)", locations: ["Kota Kinabalu","Labuan (Finance Campus)"],
    about: "UMS, established in 1994, is Sabah's premier university. Renowned for marine biology, tropical biodiversity and natural resources research. Located on the scenic Kota Kinabalu coast.",
    facilities: ["Borneo Marine Research Institute","Tropical Biodiversity Centre","Medical Faculty","Finance Campus in Labuan","Sports Complex","Student Residences"],
    fields: ["Marine Science","Business","Engineering","Medicine"],
    programs: [
      { name: "Bachelor of Science (Hons.) Marine Biology", level: "Bachelor", field: "Natural Sciences", fee: 14000, duration: 3, campus: "Kota Kinabalu" },
      { name: "Bachelor of Medicine & Surgery", level: "Bachelor", field: "Medicine", fee: 24000, duration: 5, campus: "Kota Kinabalu" },
      { name: "Bachelor of Engineering (Hons.) Petroleum", level: "Bachelor", field: "Engineering", fee: 16000, duration: 4, campus: "Kota Kinabalu" },
      { name: "Bachelor of Accountancy (Hons.)", level: "Bachelor", field: "Business & Management", fee: 11000, duration: 3, campus: "Kota Kinabalu" },
      { name: "Diploma in Finance", level: "Diploma", field: "Business & Management", fee: 7500, duration: 2.5, campus: "Labuan" },
    ]
  },
  {
    id: "unimas", name: "Universiti Malaysia Sarawak (UNIMAS)", icon: "🌴", type: "public",
    city: "Kota Samarahan", state: "Sarawak", qs: null, est: 1992,
    tuition: "RM 10,000–26,000", website: "https://www.unimas.my",
    intakes: ["February", "September"], offerLetterFee: "Free",
    ielts: "5.0 (UG) / 5.5 (PG)", locations: ["Kota Samarahan, Sarawak"],
    about: "UNIMAS, established in 1992, is Sarawak's first university. Known for cognitive science, medicine, engineering and the arts with a strong focus on Borneo's unique ecology and culture.",
    facilities: ["Sarawak Bioscience Centre","Medical Faculty","IT Innovation Hub","Arts & Design Studio","Sports Complex","Student Hostels"],
    fields: ["Engineering","Medicine","Cognitive Science","IT"],
    programs: [
      { name: "Bachelor of Medicine & Surgery (MBBS)", level: "Bachelor", field: "Medicine", fee: 26000, duration: 5, campus: "Kota Samarahan" },
      { name: "Bachelor of Cognitive Science (Hons.)", level: "Bachelor", field: "Arts & Social Sciences", fee: 13000, duration: 4, campus: "Kota Samarahan" },
      { name: "Bachelor of Engineering (Hons.) Civil", level: "Bachelor", field: "Engineering", fee: 15000, duration: 4, campus: "Kota Samarahan" },
      { name: "Bachelor of Computer Science (Hons.)", level: "Bachelor", field: "Computer Science & IT", fee: 13000, duration: 3, campus: "Kota Samarahan" },
      { name: "Master of Science in Computer Science", level: "Master", field: "Computer Science & IT", fee: 15000, duration: 1.5, campus: "Kota Samarahan" },
    ]
  },
  {
    id: "upsi", name: "Universiti Pendidikan Sultan Idris (UPSI)", icon: "📚", type: "public",
    city: "Tanjung Malim", state: "Perak", qs: null, est: 1922,
    tuition: "RM 9,000–20,000", website: "https://www.upsi.edu.my",
    intakes: ["February", "September"], offerLetterFee: "Free",
    ielts: "5.0 (UG) / 5.5 (PG)", locations: ["Tanjung Malim, Perak"],
    about: "UPSI, established in 1922, is Malaysia's oldest teacher training institution and a leading university for education studies, sports science and the arts.",
    facilities: ["Sports Academy","Arts Centre","Education Research Institute","Library","Teacher Training Labs","Student Residences"],
    fields: ["Education","Sports Science","Arts","Languages"],
    programs: [
      { name: "Bachelor of Education (Hons.) Teaching English as a Second Language (TESL)", level: "Bachelor", field: "Education", fee: 12000, duration: 4, campus: "Tanjung Malim" },
      { name: "Bachelor of Education (Hons.) Physical Education", level: "Bachelor", field: "Education", fee: 11000, duration: 4, campus: "Tanjung Malim" },
      { name: "Bachelor of Sport Science (Hons.)", level: "Bachelor", field: "Education", fee: 12000, duration: 3, campus: "Tanjung Malim" },
      { name: "Bachelor of Arts (Hons.) Music", level: "Bachelor", field: "Art & Design", fee: 11000, duration: 3, campus: "Tanjung Malim" },
      { name: "Master of Education", level: "Master", field: "Education", fee: 15000, duration: 1.5, campus: "Tanjung Malim" },
    ]
  },
  {
    id: "usim", name: "Universiti Sains Islam Malaysia (USIM)", icon: "☪️", type: "public",
    city: "Nilai", state: "Negeri Sembilan", qs: null, est: 1998,
    tuition: "RM 10,000–28,000", website: "https://www.usim.edu.my",
    intakes: ["February", "September"], offerLetterFee: "Free",
    ielts: "5.5 (UG) / 6.0 (PG)", locations: ["Nilai, Negeri Sembilan"],
    about: "USIM integrates Islamic values into modern academic disciplines. Established in 1998, it offers medicine, dentistry, Islamic finance, and Shariah programs with both Arabic and English instruction.",
    facilities: ["Medical Faculty","Dental Clinic","Islamic Finance Lab","Arabic Language Centre","Mosque","Student Residences"],
    fields: ["Islamic Finance","Medicine","Dentistry","Shariah"],
    programs: [
      { name: "Bachelor of Medicine & Surgery (MBBS)", level: "Bachelor", field: "Medicine", fee: 28000, duration: 5, campus: "Nilai" },
      { name: "Bachelor of Dental Surgery", level: "Bachelor", field: "Medicine", fee: 26000, duration: 5, campus: "Nilai" },
      { name: "Bachelor of Economics (Hons.) Islamic Finance", level: "Bachelor", field: "Business & Management", fee: 12000, duration: 3, campus: "Nilai" },
      { name: "Bachelor of Shariah (Hons.)", level: "Bachelor", field: "Islamic Studies", fee: 10000, duration: 3, campus: "Nilai" },
      { name: "Master of Islamic Finance", level: "Master", field: "Business & Management", fee: 18000, duration: 1.5, campus: "Nilai" },
    ]
  },
  {
    id: "uthm", name: "Universiti Tun Hussein Onn Malaysia (UTHM)", icon: "🔧", type: "public",
    city: "Batu Pahat", state: "Johor", qs: null, est: 1993,
    tuition: "RM 10,000–22,000", website: "https://www.uthm.edu.my",
    intakes: ["February", "September"], offerLetterFee: "Free",
    ielts: "5.0 (UG) / 5.5 (PG)", locations: ["Batu Pahat, Johor","Pagoh Campus"],
    about: "UTHM, established in 1993, is Malaysia's technical university of the south. Specialising in engineering, technology and vocational education, it produces highly skilled technical graduates.",
    facilities: ["Engineering Labs","Vocational Training Centres","Research Institutes","Sports Complex","Student Residences","Industry Collaboration Hub"],
    fields: ["Engineering","Technology","Vocational Education"],
    programs: [
      { name: "Bachelor of Engineering (Hons.) Mechanical", level: "Bachelor", field: "Engineering", fee: 14000, duration: 4, campus: "Batu Pahat" },
      { name: "Bachelor of Engineering (Hons.) Electrical", level: "Bachelor", field: "Engineering", fee: 14000, duration: 4, campus: "Batu Pahat" },
      { name: "Bachelor of Technology (Hons.) Maintenance Engineering", level: "Bachelor", field: "Engineering", fee: 13000, duration: 4, campus: "Batu Pahat" },
      { name: "Diploma in Mechanical Engineering", level: "Diploma", field: "Engineering", fee: 8000, duration: 3, campus: "Batu Pahat" },
      { name: "Master of Engineering (Manufacturing)", level: "Master", field: "Engineering", fee: 16000, duration: 1.5, campus: "Batu Pahat" },
    ]
  },
  {
    id: "utem", name: "Universiti Teknikal Malaysia Melaka (UTeM)", icon: "🛠️", type: "public",
    city: "Durian Tunggal", state: "Melaka", qs: null, est: 2000,
    tuition: "RM 10,000–22,000", website: "https://www.utem.edu.my",
    intakes: ["February", "September"], offerLetterFee: "Free",
    ielts: "5.0 (UG) / 5.5 (PG)", locations: ["Durian Tunggal, Melaka"],
    about: "UTeM, established in 2000, is Melaka's technical university. Specialising in electrical engineering, mechanical engineering, ICT and manufacturing engineering.",
    facilities: ["Advanced Manufacturing Lab","Robotics Centre","ICT Labs","Design Studio","Sports Complex","Student Hostels"],
    fields: ["Electrical Engineering","Mechanical Engineering","ICT","Manufacturing"],
    programs: [
      { name: "Bachelor of Engineering (Hons.) Electronics", level: "Bachelor", field: "Engineering", fee: 13000, duration: 4, campus: "Melaka" },
      { name: "Bachelor of Engineering (Hons.) Manufacturing", level: "Bachelor", field: "Engineering", fee: 13000, duration: 4, campus: "Melaka" },
      { name: "Bachelor of Computer Science (Hons.)", level: "Bachelor", field: "Computer Science & IT", fee: 12000, duration: 3, campus: "Melaka" },
      { name: "Diploma in Electrical Engineering", level: "Diploma", field: "Engineering", fee: 8000, duration: 3, campus: "Melaka" },
    ]
  },
  {
    id: "umpsa", name: "Universiti Malaysia Pahang Al-Sultan Abdullah (UMPSA)", icon: "⛏️", type: "public",
    city: "Gambang", state: "Pahang", qs: null, est: 2002,
    tuition: "RM 10,000–22,000", website: "https://www.umpsa.edu.my",
    intakes: ["February", "September"], offerLetterFee: "Free",
    ielts: "5.0 (UG) / 5.5 (PG)", locations: ["Gambang","Pekan Campus"],
    about: "UMPSA (formerly UMP) was established in 2002. It specialises in chemical, mechanical, and automotive engineering with a strong industry partnership model.",
    facilities: ["Chemical Engineering Lab","Automotive Engineering Centre","Research & Innovation Park","Sports Complex","Pekan Royal Campus"],
    fields: ["Chemical Engineering","Mechanical Engineering","Computing"],
    programs: [
      { name: "Bachelor of Engineering (Hons.) Chemical", level: "Bachelor", field: "Engineering", fee: 14000, duration: 4, campus: "Gambang" },
      { name: "Bachelor of Engineering (Hons.) Mechanical (Automotive)", level: "Bachelor", field: "Engineering", fee: 14000, duration: 4, campus: "Pekan" },
      { name: "Bachelor of Computer Science (Hons.)", level: "Bachelor", field: "Computer Science & IT", fee: 12000, duration: 3, campus: "Gambang" },
      { name: "Diploma in Chemical Engineering", level: "Diploma", field: "Engineering", fee: 8000, duration: 3, campus: "Gambang" },
    ]
  },
  {
    id: "unimap", name: "Universiti Malaysia Perlis (UniMAP)", icon: "🔌", type: "public",
    city: "Arau", state: "Perlis", qs: null, est: 2001,
    tuition: "RM 10,000–22,000", website: "https://www.unimap.edu.my",
    intakes: ["February", "September"], offerLetterFee: "Free",
    ielts: "5.0 (UG) / 5.5 (PG)", locations: ["Arau, Perlis"],
    about: "UniMAP, established in 2001, is Malaysia's northern engineering university. Specialising in microelectronics, electrical engineering and materials science.",
    facilities: ["Microelectronics Lab","Semiconductor Research Centre","Engineering Workshops","Library","Sports Facilities"],
    fields: ["Engineering","Microelectronics","Business"],
    programs: [
      { name: "Bachelor of Engineering (Hons.) Electrical (Power)", level: "Bachelor", field: "Engineering", fee: 13000, duration: 4, campus: "Arau" },
      { name: "Bachelor of Engineering (Hons.) Microelectronics", level: "Bachelor", field: "Engineering", fee: 13000, duration: 4, campus: "Arau" },
      { name: "Bachelor of Business Administration (Hons.)", level: "Bachelor", field: "Business & Management", fee: 10000, duration: 3, campus: "Arau" },
      { name: "Diploma in Electronic Engineering", level: "Diploma", field: "Engineering", fee: 7500, duration: 3, campus: "Arau" },
    ]
  },
  {
    id: "umt", name: "Universiti Malaysia Terengganu (UMT)", icon: "⚓", type: "public",
    city: "Kuala Nerus", state: "Terengganu", qs: null, est: 1979,
    tuition: "RM 10,000–22,000", website: "https://www.umt.edu.my",
    intakes: ["February", "September"], offerLetterFee: "Free",
    ielts: "5.0 (UG) / 5.5 (PG)", locations: ["Kuala Nerus, Terengganu"],
    about: "UMT, established in 1979, is Malaysia's ocean university. Specialising in marine science, fisheries, maritime technology and oceanography.",
    facilities: ["Marine Research Institute","Aquaculture Facility","Maritime Lab","Oceanography Centre","Sports Complex","Beachfront Campus"],
    fields: ["Marine Science","Maritime","Fisheries","Oceanography"],
    programs: [
      { name: "Bachelor of Science (Hons.) Marine Biology", level: "Bachelor", field: "Natural Sciences", fee: 13000, duration: 3, campus: "Kuala Nerus" },
      { name: "Bachelor of Science (Hons.) Fisheries", level: "Bachelor", field: "Agriculture & Forestry", fee: 12000, duration: 3, campus: "Kuala Nerus" },
      { name: "Bachelor of Engineering (Hons.) Maritime Technology", level: "Bachelor", field: "Engineering", fee: 14000, duration: 4, campus: "Kuala Nerus" },
      { name: "Master of Science (Oceanography)", level: "Master", field: "Natural Sciences", fee: 14000, duration: 1.5, campus: "Kuala Nerus" },
    ]
  },
  {
    id: "umk", name: "Universiti Malaysia Kelantan (UMK)", icon: "🌾", type: "public",
    city: "Bachok", state: "Kelantan", qs: null, est: 2006,
    tuition: "RM 9,000–20,000", website: "https://www.umk.edu.my",
    intakes: ["February", "September"], offerLetterFee: "Free",
    ielts: "5.0 (UG) / 5.5 (PG)", locations: ["Bachok, Kelantan","Kota Bharu City Campus"],
    about: "UMK, established in 2006, focuses on entrepreneurship, agro-based industry, creative technology and the environment — unique in Malaysia's university landscape.",
    facilities: ["Agro-tech Farm","Creative Design Studio","Entrepreneurship Hub","Research Incubator","Sports Facilities"],
    fields: ["Agro-business","Entrepreneurship","Creative Technology"],
    programs: [
      { name: "Bachelor of Agro-based Industry (Hons.)", level: "Bachelor", field: "Agriculture & Forestry", fee: 11000, duration: 3, campus: "Bachok" },
      { name: "Bachelor of Entrepreneurship (Hons.)", level: "Bachelor", field: "Business & Management", fee: 10000, duration: 3, campus: "Bachok" },
      { name: "Bachelor of Creative Technology & Heritage (Hons.)", level: "Bachelor", field: "Art & Design", fee: 11000, duration: 3, campus: "Kota Bharu" },
      { name: "Diploma in Agribusiness", level: "Diploma", field: "Agriculture & Forestry", fee: 7000, duration: 2.5, campus: "Bachok" },
    ]
  },
  {
    id: "uniszа", name: "Universiti Sultan Zainal Abidin (UniSZA)", icon: "🩺", type: "public",
    city: "Kuala Terengganu", state: "Terengganu", qs: null, est: 2006,
    tuition: "RM 10,000–26,000", website: "https://www.unisza.edu.my",
    intakes: ["February", "September"], offerLetterFee: "Free",
    ielts: "5.0 (UG) / 5.5 (PG)", locations: ["Kuala Terengganu, Terengganu"],
    about: "UniSZA, established in 2006, offers medicine, Islamic studies, law and science programs. The only public university in Terengganu with a medical faculty.",
    facilities: ["Medical Faculty","Islamic Studies Centre","Law Faculty","Science Labs","Sports Complex"],
    fields: ["Medicine","Islamic Studies","Law","Sciences"],
    programs: [
      { name: "Bachelor of Medicine & Surgery (MBBS)", level: "Bachelor", field: "Medicine", fee: 26000, duration: 5, campus: "Kuala Terengganu" },
      { name: "Bachelor of Shariah & Civil Law (Hons.)", level: "Bachelor", field: "Law", fee: 12000, duration: 4, campus: "Kuala Terengganu" },
      { name: "Bachelor of Science (Hons.) Biomedical Science", level: "Bachelor", field: "Medicine", fee: 13000, duration: 3, campus: "Kuala Terengganu" },
      { name: "Master of Islamic Studies", level: "Master", field: "Islamic Studies", fee: 13000, duration: 1.5, campus: "Kuala Terengganu" },
    ]
  },
  {
    id: "upnm", name: "Universiti Pertahanan Nasional Malaysia (UPNM)", icon: "🎖️", type: "public",
    city: "Kuala Lumpur", state: "WP Kuala Lumpur", qs: null, est: 2006,
    tuition: "RM 12,000–24,000", website: "https://www.upnm.edu.my",
    intakes: ["February", "September"], offerLetterFee: "Free",
    ielts: "5.5 (UG) / 6.0 (PG)", locations: ["Kem Sg. Besi, Kuala Lumpur"],
    about: "UPNM is Malaysia's national defence university, established in 2006. It offers defence studies, engineering and medicine for both civilian and military students.",
    facilities: ["Military Training Facilities","Medical Faculty","Engineering Labs","Defence Research Centre","Sports Complex"],
    fields: ["Defence Studies","Engineering","Medicine"],
    programs: [
      { name: "Bachelor of Engineering (Hons.) Electrical", level: "Bachelor", field: "Engineering", fee: 16000, duration: 4, campus: "Kuala Lumpur" },
      { name: "Bachelor of Medicine & Surgery", level: "Bachelor", field: "Medicine", fee: 24000, duration: 5, campus: "Kuala Lumpur" },
      { name: "Bachelor of Defence Studies (Hons.)", level: "Bachelor", field: "Arts & Social Sciences", fee: 13000, duration: 3, campus: "Kuala Lumpur" },
      { name: "Master of Defence & Strategic Studies", level: "Master", field: "Arts & Social Sciences", fee: 16000, duration: 1.5, campus: "Kuala Lumpur" },
    ]
  },
  {
    id: "uniten", name: "Universiti Tenaga Nasional (UNITEN)", icon: "⚡", type: "private",
    city: "Kajang", state: "Selangor", qs: null, est: 1976,
    tuition: "RM 22,000–42,000", website: "https://www.uniten.edu.my",
    intakes: ["February", "September"], offerLetterFee: "Free",
    ielts: "5.5 (UG) / 6.0 (PG)", locations: ["Kajang, Selangor","Putrajaya Campus"],
    about: "UNITEN, established by national utility company Tenaga Nasional Berhad (TNB), specialises in power engineering, energy technology and business. Strong industry connections for career placement.",
    facilities: ["Power System Lab","Smart Energy Centre","Business School","IT Labs","Sports Complex","Student Village"],
    fields: ["Power Engineering","Energy","Business","IT"],
    programs: [
      { name: "Bachelor of Engineering (Hons.) Electrical Power", level: "Bachelor", field: "Engineering", fee: 38000, duration: 4, campus: "Kajang" },
      { name: "Bachelor of Engineering (Hons.) Mechanical", level: "Bachelor", field: "Engineering", fee: 36000, duration: 4, campus: "Kajang" },
      { name: "Bachelor of Computer Science (Hons.)", level: "Bachelor", field: "Computer Science & IT", fee: 28000, duration: 3, campus: "Kajang" },
      { name: "Bachelor of Business Administration (Hons.)", level: "Bachelor", field: "Business & Management", fee: 24000, duration: 3, campus: "Kajang" },
      { name: "Master of Business Administration", level: "Master", field: "Business & Management", fee: 32000, duration: 1.5, campus: "Putrajaya" },
    ]
  },

  /* ── LANGUAGE CENTRES ── */
  {
    id: "britishcouncil", name: "British Council Malaysia", icon: "🇬🇧", type: "language",
    city: "Kuala Lumpur", state: "WP Kuala Lumpur", qs: null, est: 1948,
    tuition: "RM 2,000–8,000", website: "https://www.britishcouncil.org.my",
    intakes: ["Monthly"], offerLetterFee: "N/A",
    ielts: "No IELTS required", locations: ["Kuala Lumpur","Penang","Kota Kinabalu"],
    about: "British Council Malaysia is the UK's international organisation for educational opportunities. They offer official IELTS testing, English language courses, and professional development programmes.",
    facilities: ["IELTS Test Centre","Learning Resource Library","Professional Development Hub"],
    fields: ["English Language","IELTS Preparation","Academic English"],
    programs: [
      { name: "IELTS Academic Prep", level: "Certificate", field: "IELTS Preparation", fee: 4500, duration: 0.25, campus: "Kuala Lumpur" },
      { name: "IELTS General Training", level: "Certificate", field: "IELTS Preparation", fee: 4000, duration: 0.25, campus: "Kuala Lumpur" },
      { name: "General English A1-C1", level: "Certificate", field: "English Language", fee: 2500, duration: 0.25, campus: "Kuala Lumpur" },
      { name: "Business English", level: "Certificate", field: "English Language", fee: 3500, duration: 0.25, campus: "Kuala Lumpur" },
      { name: "Academic English for University", level: "Certificate", field: "Academic English", fee: 5000, duration: 0.5, campus: "Kuala Lumpur" },
    ]
  },
  {
    id: "ef", name: "EF Education First Malaysia", icon: "🌐", type: "language",
    city: "Kuala Lumpur", state: "WP Kuala Lumpur", qs: null, est: 1965,
    tuition: "RM 3,000–12,000", website: "https://www.ef.com/wwen/english-schools/malaysia/kuala-lumpur/",
    intakes: ["Monthly"], offerLetterFee: "N/A",
    ielts: "No IELTS required", locations: ["Kuala Lumpur"],
    about: "EF Education First is the world's largest private education company, offering English language courses, cultural exchange programmes, and IELTS/TOEFL preparation.",
    facilities: ["Modern Classrooms","Computer Lab","Student Lounge","Online Learning Platform"],
    fields: ["English Language","IELTS Preparation","TOEFL Preparation"],
    programs: [
      { name: "General English", level: "Certificate", field: "English Language", fee: 3500, duration: 0.25, campus: "Kuala Lumpur" },
      { name: "IELTS Intensive", level: "Certificate", field: "IELTS Preparation", fee: 6000, duration: 0.25, campus: "Kuala Lumpur" },
      { name: "TOEFL Preparation", level: "Certificate", field: "TOEFL Preparation", fee: 5500, duration: 0.25, campus: "Kuala Lumpur" },
      { name: "Business English Professional", level: "Certificate", field: "English Language", fee: 4500, duration: 0.25, campus: "Kuala Lumpur" },
    ]
  },
  {
    id: "berlitz", name: "Berlitz Language Centre Malaysia", icon: "🗣️", type: "language",
    city: "Kuala Lumpur", state: "WP Kuala Lumpur", qs: null, est: 1878,
    tuition: "RM 2,500–10,000", website: "https://www.berlitz.com/en-my",
    intakes: ["Monthly"], offerLetterFee: "N/A",
    ielts: "No IELTS required", locations: ["Kuala Lumpur","Johor Bahru"],
    about: "Berlitz is a world-renowned language learning company offering English, Japanese, Korean, Mandarin and other languages using the immersive Berlitz Method.",
    facilities: ["Language Labs","Private Study Rooms","Cultural Immersion Activities"],
    fields: ["English Language","Japanese Language","Korean Language","Mandarin"],
    programs: [
      { name: "English Intensive", level: "Certificate", field: "English Language", fee: 3500, duration: 0.25, campus: "Kuala Lumpur" },
      { name: "Business English", level: "Certificate", field: "English Language", fee: 4500, duration: 0.25, campus: "Kuala Lumpur" },
      { name: "Japanese Beginner-Advanced", level: "Certificate", field: "Japanese Language", fee: 5000, duration: 0.5, campus: "Kuala Lumpur" },
      { name: "Korean Language", level: "Certificate", field: "Korean Language", fee: 4500, duration: 0.5, campus: "Kuala Lumpur" },
      { name: "Mandarin", level: "Certificate", field: "Mandarin", fee: 4000, duration: 0.5, campus: "Kuala Lumpur" },
    ]
  },
  {
    id: "wallstreet", name: "Wall Street English Malaysia", icon: "🗽", type: "language",
    city: "Kuala Lumpur", state: "WP Kuala Lumpur", qs: null, est: 1972,
    tuition: "RM 3,000–15,000", website: "https://www.wallstreetenglish.com.my",
    intakes: ["Monthly"], offerLetterFee: "N/A",
    ielts: "No IELTS required", locations: ["Kuala Lumpur","Penang"],
    about: "Wall Street English specializes in English language learning for adults, using a blended learning method combining self-study, social club activities, and face-to-face lessons.",
    facilities: ["Social Club","Self-Study Room","Online Platform","Face-to-Face Lessons"],
    fields: ["English Language","Business English","IELTS Preparation"],
    programs: [
      { name: "Foundation English", level: "Certificate", field: "English Language", fee: 3000, duration: 0.25, campus: "Kuala Lumpur" },
      { name: "Upper Intermediate English", level: "Certificate", field: "English Language", fee: 4000, duration: 0.25, campus: "Kuala Lumpur" },
      { name: "IELTS Preparation", level: "Certificate", field: "IELTS Preparation", fee: 5000, duration: 0.25, campus: "Kuala Lumpur" },
      { name: "Business English Executive", level: "Certificate", field: "Business English", fee: 6000, duration: 0.25, campus: "Kuala Lumpur" },
    ]
  },
  {
    id: "erican", name: "Erican Language Centre", icon: "📖", type: "language",
    city: "Kuala Lumpur", state: "WP Kuala Lumpur", qs: null, est: 1985,
    tuition: "RM 1,500–6,000", website: "https://www.erican.edu.my",
    intakes: ["Monthly","Quarterly"], offerLetterFee: "Free",
    ielts: "No IELTS required", locations: ["Kuala Lumpur","Penang","Johor Bahru","Kota Kinabalu"],
    about: "Erican Language Centre is one of Malaysia's leading language schools, offering English, Mandarin, and other language programmes at affordable rates.",
    facilities: ["Modern Classrooms","Computer-Assisted Learning","Student Activities Centre"],
    fields: ["English Language","IELTS Preparation","Mandarin","Academic English"],
    programs: [
      { name: "IELTS Academic", level: "Certificate", field: "IELTS Preparation", fee: 3200, duration: 0.25, campus: "Kuala Lumpur" },
      { name: "General English", level: "Certificate", field: "English Language", fee: 1800, duration: 0.25, campus: "Kuala Lumpur" },
      { name: "Foundation English", level: "Certificate", field: "English Language", fee: 2500, duration: 0.25, campus: "Kuala Lumpur" },
      { name: "Mandarin Beginner", level: "Certificate", field: "Mandarin", fee: 2000, duration: 0.25, campus: "Kuala Lumpur" },
      { name: "Business Communication", level: "Certificate", field: "English Language", fee: 2800, duration: 0.25, campus: "Kuala Lumpur" },
    ]
  },
  {
    id: "sunwaylang", name: "Sunway Language Centre", icon: "🌟", type: "language",
    city: "Subang Jaya", state: "Selangor", qs: null, est: 1996,
    tuition: "RM 2,000–7,000", website: "https://university.sunway.edu.my",
    intakes: ["Monthly","Semester"], offerLetterFee: "Free",
    ielts: "No IELTS required", locations: ["Subang Jaya"],
    about: "Sunway Language Centre offers intensive English language programmes designed to prepare international students for academic study at Sunway University and other Malaysian institutions.",
    facilities: ["University Library Access","IELTS Test Centre","Student Union","Sports Facilities"],
    fields: ["English Language","IELTS Preparation","Academic English"],
    programs: [
      { name: "Pre-University English Foundation", level: "Certificate", field: "Academic English", fee: 5500, duration: 0.5, campus: "Subang Jaya" },
      { name: "IELTS Academic Preparation", level: "Certificate", field: "IELTS Preparation", fee: 4000, duration: 0.25, campus: "Subang Jaya" },
      { name: "General English", level: "Certificate", field: "English Language", fee: 2500, duration: 0.25, campus: "Subang Jaya" },
      { name: "English for Academic Purposes", level: "Certificate", field: "Academic English", fee: 3500, duration: 0.25, campus: "Subang Jaya" },
    ]
  },
  {
    id: "taylorslang", name: "Taylor's Language Programme", icon: "🏅", type: "language",
    city: "Subang Jaya", state: "Selangor", qs: null, est: 1969,
    tuition: "RM 2,500–8,000", website: "https://university.taylors.edu.my",
    intakes: ["Monthly","Trimester"], offerLetterFee: "Free",
    ielts: "No IELTS required", locations: ["Subang Jaya"],
    about: "Taylor's Language Programme provides intensive English courses to help students meet the language requirements for entry into Taylor's University programmes and other institutions in Malaysia.",
    facilities: ["Taylor's University Facilities","Library","Sports Complex","Student Services"],
    fields: ["English Language","Academic English","IELTS Preparation"],
    programs: [
      { name: "IELTS Preparation Intensive", level: "Certificate", field: "IELTS Preparation", fee: 4500, duration: 0.25, campus: "Subang Jaya" },
      { name: "English Foundation for Degree", level: "Certificate", field: "Academic English", fee: 6000, duration: 0.5, campus: "Subang Jaya" },
      { name: "General English", level: "Certificate", field: "English Language", fee: 2800, duration: 0.25, campus: "Subang Jaya" },
      { name: "Business English", level: "Certificate", field: "English Language", fee: 3200, duration: 0.25, campus: "Subang Jaya" },
    ]
  },
  {
    id: "helplang", name: "HELP Language Centre", icon: "🎓", type: "language",
    city: "Kuala Lumpur", state: "WP Kuala Lumpur", qs: null, est: 1986,
    tuition: "RM 2,000–7,500", website: "https://www.help.edu.my",
    intakes: ["Monthly","Semester"], offerLetterFee: "Free",
    ielts: "No IELTS required", locations: ["Kuala Lumpur"],
    about: "HELP Language Centre offers a comprehensive range of English language programmes, from basic communication to advanced academic English, preparing students for higher education.",
    facilities: ["Modern Labs","Library","Student Counselling","Career Services"],
    fields: ["English Language","Academic English","IELTS Preparation"],
    programs: [
      { name: "Beginner English", level: "Certificate", field: "English Language", fee: 2000, duration: 0.25, campus: "Kuala Lumpur" },
      { name: "Intermediate English", level: "Certificate", field: "English Language", fee: 2500, duration: 0.25, campus: "Kuala Lumpur" },
      { name: "IELTS Academic Preparation", level: "Certificate", field: "IELTS Preparation", fee: 4000, duration: 0.25, campus: "Kuala Lumpur" },
      { name: "Academic English for University", level: "Certificate", field: "Academic English", fee: 5500, duration: 0.5, campus: "Kuala Lumpur" },
    ]
  },
  {
    id: "cambridge", name: "Cambridge English Assessment Centre Malaysia", icon: "🎖️", type: "language",
    city: "Kuala Lumpur", state: "WP Kuala Lumpur", qs: null, est: 1913,
    tuition: "RM 1,500–5,000", website: "https://www.cambridgeenglish.org",
    intakes: ["Quarterly"], offerLetterFee: "N/A",
    ielts: "No IELTS required", locations: ["Kuala Lumpur","Penang","Johor Bahru","Kota Kinabalu"],
    about: "Cambridge English provides internationally recognised English language qualifications, including B2 First, C1 Advanced, and C2 Proficiency certificates, trusted by universities and employers worldwide.",
    facilities: ["Test Centres","Preparation Materials","Online Resources"],
    fields: ["English Language","Cambridge Qualifications","IELTS Alternative"],
    programs: [
      { name: "Cambridge B2 First Preparation", level: "Certificate", field: "Cambridge Qualifications", fee: 2500, duration: 0.25, campus: "Kuala Lumpur" },
      { name: "Cambridge C1 Advanced Preparation", level: "Certificate", field: "Cambridge Qualifications", fee: 3500, duration: 0.25, campus: "Kuala Lumpur" },
      { name: "Cambridge C2 Proficiency", level: "Certificate", field: "Cambridge Qualifications", fee: 4000, duration: 0.25, campus: "Kuala Lumpur" },
      { name: "General English Foundation", level: "Certificate", field: "English Language", fee: 2000, duration: 0.25, campus: "Kuala Lumpur" },
    ]
  },
  {
    id: "ilp", name: "ILP Language Institute Malaysia", icon: "🏫", type: "language",
    city: "Kuala Lumpur", state: "WP Kuala Lumpur", qs: null, est: 1972,
    tuition: "RM 800–3,500", website: "https://www.ilp.gov.my",
    intakes: ["Monthly","Quarterly"], offerLetterFee: "Free",
    ielts: "No IELTS required", locations: ["Kuala Lumpur","Shah Alam","Johor Bahru","Penang","Kota Kinabalu"],
    about: "ILP (Institut Latihan Perindustrian) offers government-backed English and language training programmes across Malaysia at very affordable rates, focusing on practical communication skills.",
    facilities: ["Training Classrooms","Language Labs","Government Certification","Job Placement Support"],
    fields: ["English Language","Vocational English","Communication Skills"],
    programs: [
      { name: "Communicative English Level 1", level: "Certificate", field: "English Language", fee: 1000, duration: 0.25, campus: "Kuala Lumpur" },
      { name: "Communicative English Level 2", level: "Certificate", field: "English Language", fee: 1200, duration: 0.25, campus: "Kuala Lumpur" },
      { name: "Business Communication", level: "Certificate", field: "Communication Skills", fee: 1500, duration: 0.25, campus: "Kuala Lumpur" },
      { name: "IELTS Basic Preparation", level: "Certificate", field: "English Language", fee: 2500, duration: 0.25, campus: "Kuala Lumpur" },
    ]
  }
];
